### ISSUE TITLE
Trouble installing quill locally

### ISSUE THREAD

**Issue by grueneedv** [techx/quill#67]
I followed the setup infos (which in my opinion are very reduced) to get quill locally running. After running git clone https://github.com/techx/quill and npm install on a Centos 6.9 I got the message:

> node-sass@3.14.0-0 install /var/www/html/quill/node_modules/gulp-sass/node_modules/node-sass
node scripts/install.js
/var/www/html/quill/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/quill/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0

Any hints how to resolve this? Whats the preferred system it runs on locally?

**Comment by at0dd** [comment]
I just tried an install on Centos 6.9 x64 and you might look into upgrading your gcc compiler. I believe the default is 4.4 and node-sass requires 4.6+. 

I was able to upgrade gcc to 7.2 with the following commands from [SoftwareCollections](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/):
`sudo yum install centos-release-scl`
`sudo yum install devtoolset-7`
`scl enable devtoolset-7 bash`

**Comment by grueneedv** [comment]
Thanks for the reply, that helped me getting further. 
I changed in .env the database string to DATABASE='mongodb://localhost:27017' and now I'm stuck running gulp server with the message:

> gulp server
Error: Cannot find module 'lodash.assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/quill/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I tried with the usual bash and with the devtoolset-7 bash, same result. At this point here the question again: Whats the preferred system it runs on locally?

**Comment by at0dd** [comment]
What version of node are you running? [Try upgrading to 8.9](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora).
Node is pretty universal - there's not really a 'preferred system'. If you really want to try another distro I'd suggest Ubuntu.

**Comment by grueneedv** [comment]
Thanks again for the reply and help. I just run yum install npm which installed a nodejs Version 0.10.4? or something. After adding the node repro and installing 9.6.1 it worked. 
So the installation instructions should be extended, and as requirements should be added you need NodeJS Version 8 at and a gcc > 4.6. at least?
