### ISSUE TITLE
Problems with smtp

### ISSUE THREAD

**Issue by lgg** [techx/quill#71]
```
POST /auth/verify/resend 200 8.227 ms - -
{ Error: Connection timeout
    at SMTPConnection._formatError (/var/twww/dashboard/node_modules/smtp-connection/src/smtp-connection.js:384:15)
    at SMTPConnection._onError (/var/twww/dashboard/node_modules/smtp-connection/src/smtp-connection.js:374:29)
    at SMTPConnection.<anonymous> (/var/twww/dashboard/node_modules/smtp-connection/src/smtp-connection.js:163:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5) code: 'ETIMEDOUT' }
```

**Comment by lgg** [comment]
Sorry: miss typed SMTP server url in `.env`
